# encoding: utf-8

QUESTIONS = {
    127: u'127|Suomessa on liian helppo elää sosiaaliturvan varassa',
    128: u'128|Kaupan ja muiden liikkeiden aukioloajat on vapautettava.',
    129: u'129|Suomessa on siirryttävä perustuloon joka korvaisi nykyisen sosiaaliturvan vähimmäistason.',
    130: u'130|Työntekijälle on turvattava lailla minimityöaika.',
    131: u'131|Ansiosidonnaisen työttömyysturvan kestoa pitää lyhentää.',
    132: u'132|Euron ulkopuolella Suomi pärjäisi paremmin.',
    133: u'133|Ruoan verotusta on varaa kiristää.',
    134: u'134|Valtion ja kuntien taloutta on tasapainotettava ensisijaisesti leikkaamalla menoja.',
    135: u'135|Lapsilisiä on korotettava ja laitettava verolle.',
    136: u'136|Suomella ei ole varaa nykyisen laajuisiin sosiaali- ja terveyspalveluihin.',
    137: u'137|Nato-jäsenyys vahvistaisi Suomen turvallisuuspoliittista asemaa.',
    138: u'138|Suomeen tarvitaan enemmän poliiseja.',
    139: u'139|Maahanmuuttoa Suomeen on rajoitettava terrorismin uhan vuoksi.',
    140: u'140|Venäjän etupiiripolitiikka on uhka Suomelle.',
    141: u'141|Verkkovalvonnassa valtion turvallisuus on tärkeämpää kuin kansalaisten yksityisyyden suoja.',
    142: u'142|Suomen on osallistuttava Isisin vastaiseen taisteluun kouluttamalla Irakin hallituksen joukkoja.',
    143: u'143|Parantumattomasti sairaalla on oltava oikeus avustettuun kuolemaan.',
    144: u'144|Terveys- ja sosiaalipalvelut on tuotettava ensijaisesti julkisina palveluina.',
    145: u'145|Viranomaisten pitää puuttua lapsiperheiden ongelmiin nykyistä herkemmin.',
    146: u'146|Vanhuksen ja hänen omaistensa vastuuta hoitokustannuksista on lisättävä.',
    147: u'147|Kansalaisten oikeus terveyspalveluihin on tärkeämpää kuin kuntien itsehallinto.',
    148: u'148|Ilmastonmuutoksen hillitseminen pitää asettaa teollisuuden kilpailukyvyn edelle.',
    149: u'149|Geenimuunneltu ruoka on turvallista ihmiselle ja ympäristölle.',
    150: u'150|Suomen pitää ottaa suurempi vastuu EU:n alueelle tulevista turvapaikanhakijoista.',
    151: u'151|On aika luopua ajatuksesta, että koko Suomi on pidettävä asuttuna.',
    152: u'152|Peruskoulun opetusryhmien koko on rajattava lailla esimerkiksi 20 oppilaaseen.',
    201: u'201|Suomen Nato-jäsenyydestä on järjestettävä kansanäänestys.',
    244: u'244|Hyväksytään periaatepäätös uuden ydinvoimalaitosyksikön rakentamisesta.',
    245: u'245|Tuloveroa alennetaan tasaisesti kaikissa tuloluokissa talouden elvyttämiseksi.',
    246: u'246|Edellisen eduskunnan hyväksymä lainmuutos samaa sukupuolta olevien avioliiton sallimisesta peruutetaan.',
    247: u'247|Mietojen viinien ja vahvojen oluiden myynti ruokakaupassa sallitaan.',
    248: u'248|Ruotsin kielen opiskelu muutetaan vapaaehtoiseksi.'
}